### ISSUE TITLE
Error after update from 2.5.0 to 2.7.3

### ISSUE THREAD

**Issue by TorstenBoyeImpact** [Epinova/epinova-dxp-deployment#271]
Hi,

On 2.5.0 it worked fine: 
2023-04-05T13:11:46.8784427Z Loaded cms package:    D:\a\r1\a\_Website New Build\DXC_Deployment_Package\cms.app.14662.Test1.nupkg
2023-04-05T13:11:46.8786732Z 
2023-04-05T13:11:46.8786929Z 
2023-04-05T13:11:46.9019668Z cms package 'cms.app.14662.Test1.nupkg' start upload...
2023-04-05T13:11:46.9021232Z 
2023-04-05T13:11:46.9021574Z 
2023-04-05T13:11:46.9272065Z VERBOSE: Uploading blob cms.app.14662.Test1.nupkg to storage account ...
2023-04-05T13:11:46.9273868Z 
2023-04-05T13:11:46.9274218Z 
2023-04-05T13:12:01.8069171Z VERBOSE: Done!
2023-04-05T13:12:01.8071712Z 
2023-04-05T13:12:01.8071965Z 
2023-04-05T13:12:01.8085695Z cms package 'cms.app.14662.Test1.nupkg' is uploaded.
2023-04-05T13:12:01.8088939Z 
2023-04-05T13:12:01.8089236Z 
2023-04-05T13:12:01.8534076Z VERBOSE: Starting deployment for the project: bdd6d0df-ba1a-4f1d-9d04-af3c0075982e / targetEnvironment: ADE1
2023-04-05T13:12:01.8534697Z 
2023-04-05T13:12:01.8534823Z 
2023-04-05T13:12:02.9030760Z VERBOSE: Deployment status: InProgress. Progress: 0%

On 2.7.3 we get this error:
2023-04-08T13:18:16.5945041Z Loaded cms package:    D:\a\r1\a\_Website New Build\DXC_Deployment_Package\cms.app.14667.Test1.nupkg
2023-04-08T13:18:16.5945459Z 
2023-04-08T13:18:16.5945667Z 
2023-04-08T13:18:16.6081694Z cms package 'cms.app.14667.Test1.nupkg' start upload...
2023-04-08T13:18:16.6082130Z 
2023-04-08T13:18:16.6082366Z 
2023-04-08T13:18:16.6247695Z VERBOSE: Uploading blob cms.app.14667.Test1.nupkg to storage account ...
2023-04-08T13:18:16.6248267Z 
2023-04-08T13:18:16.6248395Z 
2023-04-08T13:18:22.8494495Z VERBOSE: Done!
2023-04-08T13:18:22.8494984Z 
2023-04-08T13:18:22.8495217Z 
2023-04-08T13:18:22.8503338Z cms package 'cms.app.14667.Test1.nupkg' is uploaded.
2023-04-08T13:18:22.8503662Z 
2023-04-08T13:18:22.8503862Z 
2023-04-08T13:18:22.9119497Z ##[error]Get-ChildItem : Cannot find path 'D:\a\r1\a\_Website New 
Build\DXC_Deployment_Package\cms.app.14667.Test1.nupkg\cms.app.14667.Test1.nupkg' because it does not exist.

2023-04-08T13:18:22.9127028Z ##[error]Get-ChildItem : Cannot find path 'D:\a\r1\a\_Website New 
Build\DXC_Deployment_Package\cms.app.14667.Test1.nupkg\cms.app.14667.Test1.nupkg' because it does not exist.

2023-04-08T13:18:22.9129317Z ##[error]At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.7.3\ps_modules\EpinovaDxpDeploymentUtil.ps1
:827 char:24
+     $packageFileInfo = Get-ChildItem -Path $packageFilePath
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\a\r1\a\_Webs...667.Test1.nupkg:String) [Get-ChildItem], ItemNotFound 
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 

2023-04-08T13:18:22.9131494Z ##[error]At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.7.3\ps_modules\EpinovaDxpDeploymentUtil.ps1
:827 char:24
+     $packageFileInfo = Get-ChildItem -Path $packageFilePath
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\a\r1\a\_Webs...667.Test1.nupkg:String) [Get-ChildItem], ItemNotFound 
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 

2023-04-08T13:18:23.0877918Z VERBOSE: Exception caught from task: System.Management.Automation.PropertyNotFoundException: The property 'Name' cannot
2023-04-08T13:18:23.0878505Z  be found on this object. Verify that the property exists.
2023-04-08T13:18:23.0878785Z 
2023-04-08T13:18:23.0879166Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
2023-04-08T13:18:23.0879745Z exception)
2023-04-08T13:18:23.0879922Z 
2023-04-08T13:18:23.0880256Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2023-04-08T13:18:23.0880508Z 
2023-04-08T13:18:23.0880836Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-08T13:18:23.0881078Z 
2023-04-08T13:18:23.0881427Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-04-08T13:18:23.0881680Z 
2023-04-08T13:18:23.0881989Z    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2023-04-08T13:18:23.0882216Z 
2023-04-08T13:18:23.0882532Z    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2023-04-08T13:18:23.0882753Z 
2023-04-08T13:18:23.0883077Z    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object 
2023-04-08T13:18:23.0883410Z inputToProcess)
2023-04-08T13:18:23.0883591Z 
2023-04-08T13:18:23.0883882Z    at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2023-04-08T13:18:23.0884092Z 
2023-04-08T13:18:23.0884392Z    at System.Management.Automation.CommandProcessorBase.Complete()
2023-04-08T13:18:23.0884663Z 
2023-04-08T13:18:23.0884808Z 
2023-04-08T13:18:23.0993136Z ##[error]Get-PackageFileSize : The property 'Name' cannot be found on this object. Verify that the property exists.

2023-04-08T13:18:23.0994608Z ##[error]Get-PackageFileSize : The property 'Name' cannot be found on this object. Verify that the property exists.

2023-04-08T13:18:23.0996505Z ##[error]At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.7.3\DeployNuGetPackage.ps1:83 char:28
+ ... sFileSize = Get-PackageFileSize (Join-Path $dropPath $uploadedCmsPack ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PackageFileSize], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-PackageFileSize
 

2023-04-08T13:18:23.0998370Z ##[error]At D:\a\_tasks\DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d\2.7.3\DeployNuGetPackage.ps1:83 char:28
+ ... sFileSize = Get-PackageFileSize (Join-Path $dropPath $uploadedCmsPack ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PackageFileSize], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-PackageFileSize
 

2023-04-08T13:18:23.1317635Z Script finished

Any idea why?

**Comment by ovelartelius** [comment]
@TorstenBoyeImpact  I will have a look

**Comment by ovelartelius** [comment]
@TorstenBoyeImpact Are you running windows agent? I can see the error in the code but I want to make sure I have fixed the problem before I promise anything :)

**Comment by TorstenBoyeImpact** [comment]
Yes it is running on windows-latest agents

**Comment by ovelartelius** [comment]
@TorstenBoyeImpact I have now deployed v2.7.15. I have added a TryCatch now around the method that failed for you, + fixed a Join-Path issue, so it should not stop the deploy since it is not a important method. But I have still more fix to do. Will get back to you ASAP when everything is fixed. Working on it!

**Comment by adilkhali** [comment]
I'm having the same issue 
@TorstenBoyeImpact How do you specify the version in the YAML file?

**Comment by ovelartelius** [comment]
@TorstenBoyeImpact You don´t need to specify the version. Is more important to run a new pipeline so that you know that it is not a cached old version that will run.
I have now fixed the issue and released v2.7.16. tested on all agent types and I don´t get any errors. If you have any problem don´t hesitate to contact me.
Regards
Ove

**Comment by TorstenBoyeImpact** [comment]
Hi, @ovelartelius . Great work, it is working now. Thanks for the hot fix.
