### ISSUE TITLE
Service Principal 

### ISSUE THREAD

**Issue by zbrilhart** [Epinova/epinova-dxp-deployment#284]
Hello, do the release tasks require a service principal to work correctly? 

The following errors occurred indicating service principal should be checked. 

[error]Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg

[error]Error: Failed to fetch App Service 'appservicename' publishing credentials. Error: Could not fetch access token for Azure. Status code: invalid_client, status message:

In DxP service principals are not supported.

**Comment by ovelartelius** [comment]
Hmm.  that sounds strange. 
Which task returned that error message? Can you share the logfile for the task?

**Comment by DianaKgagz** [comment]
AzureRmWebAppDeployment Task

2023-07-20T18:11:32.7477271Z ##[section]Starting: AzureRmWebAppDeployment
2023-07-20T18:11:32.7618464Z ==============================================================================
2023-07-20T18:11:32.7618625Z Task         : Azure App Service deploy
2023-07-20T18:11:32.7618841Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2023-07-20T18:11:32.7619008Z Version      : 4.225.0
2023-07-20T18:11:32.7619073Z Author       : Microsoft Corporation
2023-07-20T18:11:32.7619148Z Help         : https://aka.ms/azureappservicetroubleshooting
2023-07-20T18:11:32.7619256Z ==============================================================================
2023-07-20T18:13:06.1445526Z Got service connection details for Azure App Service:'******inte'
2023-07-20T18:13:13.3567159Z ##[error]Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg
2023-07-20T18:13:13.3573935Z ##[error]Error: Failed to fetch App Service '******inte' publishing credentials. Error: Could not fetch access token for Azure. Status code: invalid_client, status message: 7000222 - [2023-07-20 18:13:13Z]: AADSTS7000222: The provided client secret keys for app '***' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
Trace ID: 3687b5ea-f373-4308
Correlation ID: 036e71f2-7f73
Timestamp: 2023-07-20 18:13:13Z - Correlation ID: 036e71f2-7f73 - Trace ID: 3687b5ea-f373-4308
2023-07-20T18:13:20.0128610Z ##[error]Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired. For more information refer https://aka.ms/azureappservicedeploytsg
2023-07-20T18:13:20.0176344Z (node:2508) UnhandledPromiseRejectionWarning: Error: Failed to fetch App Service 'epcr01mstrv980kinte' publishing profile. Error: Could not fetch access token for Azure. Status code: invalid_client, status message: 7000222 - [2023-07-20 18:13:19Z]: AADSTS7000222: The provided client secret keys for app '***' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
2023-07-20T18:13:20.0177255Z Trace ID: 5fea71af-f7e6
2023-07-20T18:13:20.0177618Z Correlation ID: 8138264b
2023-07-20T18:13:20.0178189Z Timestamp: 2023-07-20 18:13:19Z - Correlation ID: 8138264b-0d7d - Trace ID: 5fea71af-f7e6
2023-07-20T18:13:20.0178893Z     at AzureAppService.<anonymous> (D:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\azure-arm-app-service.js:770:23)
2023-07-20T18:13:20.0179330Z     at Generator.throw (<anonymous>)
2023-07-20T18:13:20.0930095Z     at rejected (D:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\azure-arm-app-service.js:6:65)
2023-07-20T18:13:20.0930819Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2023-07-20T18:13:20.0932910Z (node:2508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2023-07-20T18:13:20.0933714Z (node:2508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2023-07-20T18:13:20.0967734Z ##[section]Finishing: AzureRmWebAppDeployment

**Comment by ovelartelius** [comment]
Hi @DianaKgagz 
The log you sent use is not a Epinova DXP deployment task. That is a Microsoft Azure task. 
If you want to deploy to Optimizely DXP and want to use Epinova DXP extension, you can read though some of our blog posts and documentation to get more information how to setup and use Epinova DXP extension.
https://www.epinova.se/nyheter-och-blogg/utvecklarbloggen/2020/epinova-dxp-deployment-part-1-introduction/ (5 blog post series)
https://www.epinova.se/nyheter-och-blogg/utvecklarbloggen/2021/directdeploy-with-epinova-dxp-deployment/
https://github.com/Epinova/epinova-dxp-deployment/blob/master/README.md
I hope that this will help you get on the right track.
Kind regards
Ove

**Comment by ovelartelius** [comment]
@zbrilhart Was this the same problem you have or do you need more assistance?

**Comment by zbrilhart** [comment]
@ovelartelius, I was working with Diana on this, thank you for checking and all the assistance.

**Comment by zbepi** [comment]
Hello @ovelartelius, I don't know if this has been communicated to you yet but service principals for all DxP clients will eventually be expiring. Are you aware of this? 

I believe this add-on will be unusable when this happens, can you confirm?

**Comment by ovelartelius** [comment]
Hi @zbepi 
We don´t use service principal in the DXP extension tasks. Everything in the background is communicating via EPiCloud PowerShell module that talks to Optimizely Deployment API. Instead of service pricipal they are using API key and secret that is generated in the PAAS portal. 
![image](https://github.com/Epinova/epinova-dxp-deployment/assets/4722784/8606f788-7c91-4577-9c06-b55f49230dce)
So there should be no problem in my understanding. 
Starts to make me wonder. Where do you use service principal today in this context? If you don´t want to answer here you can contact me on ove.lartelius@epinova.se

**Comment by zbepi** [comment]
Thank you for this info. I was misled by a blog post, but now it is clear that the service principal expiration should not be an issue given the use of the deployment API.

Sorry for my confusion!
